name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  github:
    uses: yoriiis/actions/.github/workflows/github-pages-deploy.yml@main
    with:
      node-version: 18
      build-dir: demo/dist
      command-build: npm run build:example
