name: Lint

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    uses: yoriiis/actions/.github/workflows/lint.yml@main
    with:
      typescript-status: false
      stylelint-config: './config/stylelint.config.cjs'
      eslint-config: './config/.eslintrc.cjs'
      eslint-input: './src ./config ./demo'
      stylelint-input: './src/**/*.css ./demo/**/*.css'
